### ISSUE TITLE
Some problem of multi CPUs

### ISSUE THREAD

**Issue by Huwenbo-git** [rll-research/BPref#1]
I test the experiments on Intel Xeon Gold 5118 and GTX2080 Ti. But I found that the utilization rate of GPU is very low. It takes 10 hours to train the Walker_walk/train_ppo.sh for 3 seeds.  Is it my experimental parameters or is it normal?

**Comment by pokaxpoka** [comment]
I think there is no problem in parameters side :)

**Comment by Huwenbo-git** [comment]
Thanks for your answer!
I want to know about how to maxmize the usage of the cpu?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
