### ISSUE TITLE
GUI for preference-based RL

### ISSUE THREAD

**Issue by awesomericky** [rll-research/BPref#2]
Hello, I am currently interested in applying preference-based RL in various robotics tasks in the real world.

I read the paper "BPref" and noticed that the preference is given to the agent by various simulated teachers, not real humans, to make the training and evaluation process fast. But in your previous paper "PEBBLE", it seems that real human preferences were used.

I am curious what kind of GUI you used for the humans to interactively give preference feedback. Could you give me some tips?

cf) For the simulation environment, I am using [RaiSim](https://raisim.com/) and [Isaac gym](https://developer.nvidia.com/isaac-gym).

**Comment by familyld** [comment]
> Hello, I am currently interested in applying preference-based RL in various robotics tasks in the real world.
> 
> I read the paper "BPref" and noticed that the preference is given to the agent by various simulated teachers, not real humans, to make the training and evaluation process fast. But in your previous paper "PEBBLE", it seems that real human preferences were used.
> 
> I am curious what kind of GUI you used for the humans to interactively give preference feedback. Could you give me some tips?
> 
> cf) For the simulation environment, I am using [RaiSim](https://raisim.com/) and [Isaac gym](https://developer.nvidia.com/isaac-gym).

I am also curious about this field. Did you receive any response from the authors?

**Comment by awesomericky** [comment]
Yes. I got a response from the authors through email. They said they used jupyter notebook to show gifs of two videos and let the user interactively choose between them.

**Comment by AnukritiSinghh** [comment]
@awesomericky I am new to this field and was wondering how people get videos of for example Walker in deepmind environment? I'd appreciate any help. Thanks!
